name: Docs
on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      
      - name: Clean docs folder
        run: cargo clean --doc

      - name: Build docs
        run: cargo doc --no-deps

      - name: Archive documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: target/doc
